<?php
	$pageId = "ac";
?>

<!DOCTYPE html>
<html lang="en">
<head>

	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
	<title>Department of Archaeology</title>

	<?php require_once "../assets/header.php"; ?>
	
	<!-- begin body content -->

	<div class="container">
		<ol class="breadcrumb">
		  <li><a href="../index.php">Home</a></li>
		  <li class="active">Programmes</li>
		  <li class="active">Undergraduate Programme</li>
		</ol>
        <div class="page">
            <h3>Undergraduate Programme</h3>
            <hr />
            <div class="cList">
            <h3>Our Course Structure</h3>
            <h4>First Year Courses</h4>
            <span>ACL 101</span> <span><a href="" title="The aim of the two introductory courses in Archaeology (ACL 101 and ACL 102) is to provide students who have had no previous exposure to the discipline with an introduction to its different fields. Following an introductory session, an overview of the theoretical development of the subject, and the history of archaeology, the course moves on to the use of artifacts, primary literary sources, epigraphy, numismatics, the built environment, and pre-industrial crafts and technology as source material in interpretative archaeology.">Introductory Archaeology I</a> </span><br/>
            
            <span>ACL 102</span> <span><a href="" title="The course expects to equip the student with basic tools from the field of multi-disciplinary studies, as a point of entry into field and interpretative archaeology. It introduces the subjects of anthropology, ethno-archaeology, bio-archaeology, environmental archaeology, the different aspects of the field archaeology process, cultural heritage management, museology and computer archaeology.">Introductory Archaeology II</a> </span>
            <br/><br/>
            <!--<p>Students offering Geography in their fist-year of studies at the Faculty of Arts are required to following two courses: GGY 101 – <a href="" title="The nature and processes of geo-system and its constituent parts:  atmosphere, lithosphere, hydrosphere and biosphere; structure and composition of the atmosphere: atmospheric circulation, weather and climate, energy transmission, spatial variation of energy inputs and energy budget; structure and composition of the earth: tectonics and related processes; hydrological cycle and its components: precipitation, evapotranspiration, groundwater, surface water and the oceans; vegetation zones of the world: world soils, ecosystems, biomes, energy and matter flows.">Fundamentals of Physical Geography</a> and GGY 102 – <a href="" title="Themes and fundamentals of Human Geography: evolution of Geography and Human Geography, core geographic concepts, population dynamics and resources; geographical diversity and unity: spatial patterns of religions, language, ethnicity, social inequality; Spatial patterns of  world political economy: patterns of development and globalization, dynamic patterns of space economy (agricultural, industrial and service sector); settlements: urban systems and urban structures, political ordering of space; Applied Human Geography: human impact on natural systems : landscape, land use, environmental problems and management.  The course will heavily rely on map exercises.">Fundamentals of Human Geography.</a></p>
            <p>Students are selected for the Special Degree in Geography at the end of the first year based on their GP for Geography and the general (overall?) GPA. Additional qualifications considered in the selection of special degree students are their performance in Basic Mathematics and English as a Second Language (ESL) courses. Besides the special degree,  Geography is also offered as a subject for a General Degree.</p>-->
            <h4>Second Year Courses</h4>
            <!--<p>The second and third year courses are mostly composed of compulsory courses to ensure that students acquire a foundational knowledge and skills in Geography. </p>
            
            <span>Compulsory Credited Courses</span>
            <br/>-->         
                           

                <span>ACL 201</span> <span><a href="" title="The course introduces the concept of evolution in its many aspects: geological and biological evolution, primate and hominoid evolution, the different stages of hominid (human) evolution, variations in the physical characteristics of humans, and anthropometry (paleohuman biology). The fields of ethnography, ethnology and ethno-archaeology are defined, broadening into discussions of ethnographic theory and practice, ethnographic analogies, and field techniques.">Palaeo-Human Biology and Ethno-Archaeology</a> </span><br/>
                
                <span>ACL 202</span> <span><a href="" title="This course, along with ACL 207, guides students in the study of the historical background of ancient India and Sri Lanka, and provides them with the historical context needed to situate material evidence retrieved from archaeological studies. ACL 202 introduces the study of history and historiography, the management of historical data in archaeology, historical geography and techno-cultural periods and zones of the Indo-Pakistan subcontinent, pre-Harappan, Harappan and other Chalcolithic cultures, Early Iron Age cultures, urbanism, state formation, trade and commerce and the emergence of land grant economies.  
">Socio-Economic History of Ancient India</a></span> <br/>
                
                <span>ACL 203</span> <span><a href="" title="The student is introduced in this course to the theoretical basis of archaeological studies and to the different stages of the archaeological process from surveying and field reconnaissance, excavation, analysis, interpretation and reconstruction, to publication.">Archaeological Theory and Methods</a></span> <br/>
                <span>ACL 204 </span> <span><a href="" title="This course is designed to train the student in the various aspects involved in managing the cultural heritage.">Cultural Resource Management</a></span> <br/>
                <span>ACL 205</span> <span><a href="" title="In this course the student is provided with a basic introduction to theory, policy and practice in archaeological conservation. This covers the conservation of sites, monuments, objects and materials located in different physical environments—
from conservation up to their storage and presentation in suitable environments, and the preparation of conservation reports.">Conservation of Archaeological Material</a></span> <br/>
                <span>ACL 206</span> <span><a href="" title="The aim of this course is to provide an overview of the nature of global civilizations. It introduces the concept of material culture and civilization, ecological and human adaptations, early village cultures and bronze age urbanism. This is followed by study of certain aspects of the Mesopotamian, Egyptian, North Mediterranean, Chinese, Mesoamerican, South American, and Islamic civilizations.">Formation of Ancient Civilizations</a></span> <br/>
                <span>ACL 207</span> <span><a href="" title="The course provides an insight into concepts related to the history, historiography, historical periodisation, and historical sources of Sri Lanka. It traces the development of Sri Lankan civilization from prehistoric foraging societies to early iron age village cultures, to urbanism and state formation, agricultural expansion, water management and craft production in the Early Historic Period, the transformation to Middle Historic and Late Historic polities, and precolonial demographic shifts and new societal adaptations.">The Socio-Economic History of Ancient Sri Lanka</a></span> <br/>
                <span>ACL 208</span> <span><a href="" title="The student is trained in this course in archaeological recording practices in the field and laboratory which are not covered in ACL 203. The student is introduced to the use and production of topographical and geological maps, aerial photography and site plans, archaeological draughting practice related to sites, monuments and objects, computer archaeology in managing data bases, and Geographical Information Systems.">Practical Archaeology</a></span> <br/><br/>
                <!--<span>Compulsory Non-Credit Courses</span>
            <br/>
            <span>GGY 215</span> <span><a href="" title="Biology:
Biomolecules, cell structure and function, prokaryotes &eukaryotes, introduction to kingdoms, introduction to genetics, Basic Microbiology, Basic Ecology, biotic &abiotic interactions, geographical pattern of species & diversity, plant anatomy & morphology, plant classification  & identification, conservation biology, basic concepts of biogeography.
Chemistry:
Matter, chemical formula and bonds, introduction to periodic table, periodic table and properties of elements, chemical reactions, different types of chemical reactions, industrial applications, transition elements and properties, environmental applications, behavioral pattern of gasses, solvents, solutions and mixtures, compounds, acids and bases, domestic chemicals and their effects.
Physics:
Units of measurements, displacement, velocity, acceleration, vectors, forces, friction, Newton’s laws, gravity, waves, magnetism, light, heat and pressure, relativity, practical physics.
">Basic Science for Geography</a></span><br/>
            <span>GGY 216</span> <span><a href="" title="Sets and inequalities, Linear equations, Quadratic equations, Functions and graphs, Trigonometry, Limits  including limits at infinity and infinite limits, Continuity, Derivatives, Curve sketching, Maximum-minimum problems, Exponential and logarithmic functions, Techniques of integration, Areas and volumes, partial derivatives, Introduction to vectors,  Scalar product, Vector product, Triple scalar product, Triple vector product, Spherical trigonometry, Introduction to probability theory. 
">Mathematics for Geography</a></span><br/><br/>
            <span>Compulsory Courses outside the Discipline</span>
            <br/>
            <span>ECN 204</span> <span>Introductory Statistics</span><br/>
            <span>ECN 214</span> <span>Intermediate Statistics</span><br/><br/>-->
            <h4>Third Year Courses</h4>
                        <!--<span>Compulsory Courses</span>
            <br/>         


                <span>GGY 301</span> <span><a href="" title="The course consists of a preliminary survey of the nature of scientific inquiry and research, identification of research problems, field data collection methods inPhysical and Human geography, the application of statistical techniques: univariate and multivariate, and sampling and field study methods, the course is divided into the following sections: basic elements of research; field methods; data collection and processing; and data analysis and presentation. 
">Research Methods</a></span> <br/>
                <span>GGY 302</span> <span><a href="" title="This course covers the following topics: introduction to hydrology and its applications, hydrological cycle, Precipitation, evaporation and transpiration, infiltration, interception and depression storage, surface runoff/Stream flow, introduction to hydrographs, time series analysis, surface water and ground water quality, natural and human impact of water quality and quantity; preparation of water quality maps. 
">Introduction to Hydrology</a></span> <br/>
                <span>GGY 303</span> <span><a href="" title="Part One: Introduction to physical environment; Geology: structure and tectonics, relief and drainage, landforms, soils, minerals, water resources; Climate: circulation and seasonal regime, temperature, rainfall, and climate change; biological environment:  natural vegetation, agro-ecology,  marine environment, natural hazards and disasters: landslides, floods, droughts, cyclones, tornados, and tsunami
Part Two: Introduction to social environment; population: growth, distribution and density, ethnicity and religion, urban and rural settlements;agriculture:types and spatial patterns and major issues; Industries: types and spatial patterns and problems; Services (spatial inequalities in education, health, welfare and consumer services; patterns of international trade; challenges and opportunities: environment management, poverty eradication, national integration and globalization.
 
">Geography of Sri Lanka</a></span> <br/>
                <span>GGY 304</span> <span><a href="" title="Introduction to Surveying, different types of land surveys and instruments, measurements and errors, units, significant figures, types of errors, precision and accuracy, distance measurements, taping, electronic distance measurements, levelling, differential levelling, trigonometric levelling, adjustments, angles, bearings, azimuths, traversing, global navigation satellite systems, area calculations, closed polygons, irregular boundaries, circular boundaries.
 
">Surveying and Leveling</a></span> <br/>
                <span>GGY 305</span> <span><a href="" title="This course will critically discuss the question of “What is Geography” with reference to various approaches and traditions developed within the course of its historical evolution. Central geographical concepts: space, place, landscape region and definitions of geography; The evolution of geography emphasizing three different periods: classical (Greek and Roman geography), intermediate (contributions of Ritter and Humboldt), modern geography up to 1970s, environmental determinism, regional and systematic approach, Hartshorne-Schafer debate, spatial approach (systems analysis), Regional Science school, radical approach (liberal and Marxist Geography), behavioural and humanistic approach; Post 1990s developments in Geography and the status and the nature of Sri Lankan Geography: society and space debate, place debate, physical to environmental geography, issue of scale.  
 
">Philosophy of Geography</a></span> <br/>
                <span>GGY 310</span> <span><a href="" title="This course will cover the following topics: historical evolution of the settlements: origin and growth; types of settlements: rural, urban, and other; ecological processes of rural and urban growth; settlement functions and networks; spatial patterns of the settlements: spatial hierarchies and  internal morphologies;  settlement  and landscapes: settlements as instruments of social, economic,  colonial and cultural articulation; measuring settlement patterns: nearest neighbour analysis, the rank size rule,  primate city, central place theory;   settlement policies and planning in Sri Lanka.  
 
">Settlement of Geography</a></span> <br/>
                <span>GGY 311</span> <span><a href="" title="Introduction to Biogeography:  link between biology and geography; theoretical and conceptual development of the field; The concept of biosphere: origin and evolution of organisms; biological kingdoms; the theory of island biogeography; the concept of carrying capacity; geographical distribution of biota; biogeographic realms and major biomes: Wallace’s biogeographical regions; The concept of biodiversity: genetic diversity, species diversity and  ecosystem diversity/habitat diversity, biodiversity degradation; biological interactions.  society and biological resources: the concept of conservation, challenges and conservation measures in national and international contexts(special attention will be paid to in – situ and ex – situ conservation practices in Sri Lanka); Biological survey methods (practical exercise based on a field visit); conservation Biogeography ( The roots of conservation Biogeography, social values of conservation Biogeography, systematic conservation – past, present & future)  
 
">Biogeography</a></span> <br/>
                <span>GGY 312</span> <span><a href="" title="This course will cover the following topics: the concepts and theories of Urban Geography; the process of urbanization: origin and growth of urban settlements; evolution of urban systems: form, structure and organization of cities; urban functions: commercial, residential, services etc.; urban land use planning; urban problems and prospects; cities of future; urbanization in Sri Lanka; Urban policies and planning in Sri Lanka.  
 
">Urban Geography</a></span> <br/>
                 <br/><br/>
                 <span>Subjects outside the Discipline (two courses)</span><br/>
             
            <span>Students are required to take two optional courses from other Departments of the University.</span>--> 
                        <h4>Fourth Year Courses</h4>
                        <!--<p>In the fourth year, students have the option of specializing in either Human or Physical Geography by choosing from a range of non-compulsory courses. These courses are aimed at providing students with an in-depth knowledge and equipping them with diverse skills required to synthesize the qualitative and quantitative information in Geography. All students specializing in Geography are required to register for GGY 498 and GGY 499 for the purpose of conducting an original research on a topic of their choice and writing a dissertation under the supervision of an academic staff member.</p>
     
			<span>Compulsory Courses</span>
            <br/>       
                <span>GGY498</span> <span>Dissertation I</span> <br/>
                <span>GGY499</span> <span>Dissertation II</span> <br/><br/>
                <span>Optional Courses</span>
            <br/>
            <span>Stream I</span> <span>Human Geography </span> <br/>
                <span>GGY401</span> <span><a href="" title="The course will include the following topics: evolution of agriculture; diffusion of agricultural innovations; classification of agricultural systems; changing role of agriculture in economic development; geographical factors affecting agricultural production; models and theories in Agricultural Geography; locational decision making in agricultural production; green revolution; Major issues in agricultural geography: food security and  food crisis; agricultural geography in Sri Lanka;   challenges and opportunities,  agricultural policies, agri-business and green economy,  case study of  a selected agricultural area in Sri Lanka.">Agricultural Geography</a></span> <br/>
                <span>GGY402</span> <span><a href="" title="This course is designed to provide a broad understanding of both theoretical and practical aspects of development from a spatial perspective. The course will provide critical knowledge covering four major areas, theories of development and underdevelopment, Measuring development, political economy of development and its uneven spatial structure (core-periphery model) and major developmental issues at global scale (environmental sustainability, gender equity, third world poverty (rural and urban),  trade and aid, regionalization and globalization.  The course will draw upon the development experience of selected countries from South Asia, East Asia and Latin America.">Development Geography </a></span> <br/>
                <span>GGY403</span> <span><a href="" title="This course highlight two fundermantal points: ethnonationalism is intrinscially spatial and ethnonationali politics is a fundamental fact of modern state. The main topics covered include  link between space and politics; basic concepts of tribe, community, ethnicity, race, nation,nationalism and ethnonationalism; culture and ethnonationalism; types of nationalism; theories of ethnonationalism; ethnonationalist politics around the world : United Kingdom, Canada, India, Spain etc.; Nature of the Sri Lankan  nation-state; nature of Sinhalese ethnonationalism; nature of Tamil ethnonationalism; terrorism and Tamil ethnonationalism; nature of Muslim ethnic politics; federalism and ethnonationalism; globalization and nationalism; ethnonationalism and the future of the state.">Geography of Nationalism </a></span> <br/>
                <span>GGY404</span> <span><a href="" title="Introduction: geography of poverty; What is poverty: conceptual background of poverty, definitions of poverty (from monetary to non-monetary approaches), poverty measurement and mapping (quantitative, qualitative), the Millennium Development Goals;   Who is poor: poverty and inequality, horizontal poverty and vertical poverty; Where is poverty? : rich and poor countries, empirical understanding of poverty at different spaces/scales: poverty-urban and rural; poverty at global, national and local level (focus on Sri Lanka); poverty as a global issue: famine and hunger, poverty and health, poverty and war; age and poverty, disability and poverty, poverty and globalization; poverty alleviation policies and practices at national and international scales: Sri Lankan policies of poverty alleviation, local actions to alleviate poverty in Sri Lanka, politics of poverty.">Geography of Poverty </a></span> <br/>
                <span>GGY405</span> <span><a href="" title="Introduction:  basic concepts of geopolitics including sovereignty,  state, sphere of influence, hierarchy of states;  theories of realism and idealism; critical geopolitics; evolution of geopolitical ideas through the contribution of major thinkers of geopolitics and their influence;  cold war geopolitics;  post-cold war geopolitics;  culture and geopolitics : clash of civilizations;  modern geopolitics and its defining features; geopolitics of environment;  Indian Ocean geopolitics; changing geopolitical significance of Sri Lanka and future of Sri Lankan geopolitics.">Geopolitics </a></span> <br/>
                <span>GGY406</span> <span><a href="" title="The course will focus on two major approaches in historical geography: horizontal approach and vertical approach. After a general review of the sub discipline of Historical Geography with its specific methodologies and the concepts of history, geography and their interrelationship, this course will analyze on the historical geography of Sri Lanka through the two both these approaches.  The course will focus on the geographical patterns during ancient, pre-colonial, colonial and postcolonial periods in Sri Lanka.  The main topics covered include peopling of the island; Distribution pattern of population and settlements; transportation; migration patterns; agriculture; irrigation; natural resources utilization; political units and boundaries.">Historical Geography </a></span> <br/>
                <span>GGY407</span> <span><a href="" title="The course introduces basic principles of the location of manufacturing industries and, describes various concepts and theories that examine the location of industries from single plant/firm to large industrial corporations, with the view of spatial evolutionary patterns of industrialization, the course discusses the relationship between national economic strategies and international trends in manufacturing. Introduction to industrial geography; location factors; classical industrial location theories, neo-classical industrial location theories, co-operate growth and industrialization, trends and patterns of industrialization in the 19th, 20th and 21st  centuries; the influence of liberal economic policies on the growth of industrialization in developing countries; industrialization and its impact on the environment; industrial Geography in Sri Lanka; evolution, spatial distribution, challenges and opportunities in industrialization, industrial policy and planning in Sri Lanka.">Industrial Geography </a></span> <br/>
                <span>GGY408</span> <span><a href="" title="The course will be organized as a seminar.  Each week the students will be reading an article relevant to the particular theme and be prepared for a discussion.  The main topics to be covered are;general introduction to the concept of landscape; evolution of landscape tradition in Geography: Landschaftkunde(German tradition), Carl Sauer tradition, new cultural Geography; the relationship between landscape and culture; material recording of landscape: the morphological approach to landscape, the application of morphologic method; social construction of landscape: reading landscape as a text, landscape as theatre, rural, urban, economic, political, religio-cultural landscapes, landscapes in art and film; changing landscape of a selected city.  The students will conduct field work throughout the semester either in Kandy city or University of Peradeniya.">Landscape Geography </a></span> <br/>
                <span>GGY410</span> <span><a href="" title="This course focuses on the role of culture in shaping places, regions, and landscapes. Cultural geography is concerned with making sense of people and the places they occupy through analyses of cultural processes, cultural landscapes, and cultural identities. The course introduces culture from a geographical perspective, focusing on how cultures work in places and how they are embedded in everyday life. The course gives students an appreciation for not only how cultures are spatially expressed, but also how geography is a basic element in the constitution of culture. The course will be divided into three sections. Main theoretical shifts in the field of Anglophone cultural geography and how they evolved throughout the 20th century: Beginnings of Cultural Geography, Carl Sauer and morphological approach, emergence of New Cultural Geography with Duncan, Daniels and Cosgrove; Key concepts of Cultural Geography ;  Assessment of case studies of cultural landscapes, places, and regions and analysis of cultural geographies of religion, ethnicity and language, cultural geography of Sri Lanka and  Interpretation of cultural geography as  “power politics”  of place.">Cultural Geography </a></span> <br/>
                <span>GGY412</span> <span><a href="" title="This course will explore the relationship between social relations, identities and inequalities and geography. How social relations and identitiesvary over space and the role of space in constructing social inequalities is the main focus of social geography. The course will cover the following topics: Development of social geography as a sub¬field of human geography(both positivist and non-positivist approaches); Impact of social theories on human geography (Durkheim, Weber, Marx and Giddens, Gramsci, Foucualt, Feminist theories); social structures and spatial relations: society and space debate;   social/spatial inequalities and their implications relating to race, class, ethnicity, gender and sexuality, poverty, health and well being in varying spatial units such as the state, city and rural areas.">Social Geography </a></span> 
                <br/>
                <span>GGY413</span> <span><a href="" title="The course includes following topics: Basic concepts in Transportation Geography; geographical factors affecting transport and traffic system; transport system: air, water and surface (road and rail) networks of transportation systems; models and techniques in Transport Geography: the gravity model, networks analysis, accessibility index, connectivity index;  spatiality of transport pricing; transportation geography of Sri Lanka: analysis of  the transportation infrastructure in Sri Lanka; transportation and development; transportation problems; transport policy and planning; environmental impacts of transportation systems.">Transport Geography </a></span> 
                <br/><br/>
                <span>Stream II</span> <span>Physical Geography </span> <br/>
                <span>GGY426</span> <span><a href="" title="This course provides knowledge about changes in the terrestrial and acquatic environments caused by natural and human forcing mechanisms.  The main topics in the course includes introduction to environmental change; environmental dynamism; different types of environmental changes: terrestrial, aquatic, atmospheric; historical records and evidence of environmental change; causes of ecosystem changes; anthropogenic pressure and human responses; criteria and indicators for measuring environmental change; policy dimesions at  global, regional and national levels; environmental modelling; application of environment models. The course will consist of field work sessions involving both individual and group- based projects.">Environmental Change</a></span> <br/>
                <span>GGY427</span> <span><a href="" title="This course consists of three sections: bio-physical environment of the tropical region, contemporary problems and socio-economic challenges of the tropics: Bio-physical environment: introduction to tropical environment; tropics as a natural region; tropical regions in Africa, Latin America and Asia; tropical ecosystems; biophysical characteristics of the tropics; biogeochemical cycling and nutrient cycling in the tropical environments; development and adaptations of the vegetation; geomorphologic processes: land forms and soil of the tropics; classification of tropical climate; environmental problems: tropical deforestation; loss of biodiversity and genetic resources; pollution; desertification; land degradation; socio-economic challenges of the tropics: poverty and livelihood strategies, urban overgrowth, overpopulation; politics and economics of managing natural habitats in the tropics.">Tropical Environment </a></span> <br/>
                <span>GGY428</span> <span><a href="" title="Introduction to the field of Soil Geography; factors of soil formation; pedological processes;  nature and composition of soils: texture, structure, chemical, physical and mineralogical characteristics; Soil morphology;  soil hydrology;  major systems of soil classification: traditional and numerical methods of soil classification; spatial distribution of soils; methods of soil survey and field mapping; laboratory analysis of soil; soil as an important natural resource; current problems of soil degradation due to human use and misuse; soil conservation; soil geography of Sri Lanka;  issues, challenges and opportunities;biological properties of soil;  soil sampling methods.">Soil Geography </a></span> <br/>
                <span>GGY429</span> <span><a href="" title="The course covers the principles and techniques of fluvial processes and of landform development. The course will cover: Origin and development of drainage networks; drainage basin as a unit of landform study; drainage basin and network characteristics: physical characteristics, drainage patterns and channel flow characteristics; erosion, transport and deposition processes and related landforms; characteristics of fluvial deposits, hydraulics of erosion and sediment transport in rivers; river channel adjustment and equilibrium: long profile, cross-section and dynamic equilibrium; measurement and quantitative evaluation of drainage basin processes.">Fluvial Geomorphology </a></span> <br/>
                <span>GGY430</span> <span><a href="" title="The course provides the theoretical and practical knowledge of climate of the tropical region. The main topics covered are introduction to the tropics, solar radiation distribution, energy and mass transfers to the extra-tropical region, temperature in the tropics, the general circulation of the tropical atmosphere; the Hadley cell, the low pressure and convergent air masses-Inter-tropical Convergence Zone (ITCZ), the sub tropical highs and distribution of deserts, the trade winds, seasonal variation of tropical circulation, tropical disturbances:  thunderstorms, monsoon depressions,  easterly waves, tropical cyclones; water in the tropical atmosphere:evapo-transpiration, humidity, condensation, clouds; tropical precipitation: its origin, annual and seasonal variability, rainfall frequency and intensity, the tropical monsoon Asia, the applied tropical climatology: tropical climate and agriculture, tropical climate and water resources, and man`s adaptation to climatic extremes in the tropics;  tropical climate types and future challenges.">Tropical Climatology </a></span> <br/>
                <span>GGY431</span> <span><a href="" title="The course provides the student with the knowledge of concepts, theories and techniques in surface and groundwater hydrology and water resource management. The areas covered are hydrograph analysis; flood frequency analysis; hydrometeorological data analysis; hydrological modelling; groundwater as a natural resource: major aquifers,  ground water movements; major water resource issues in Sri Lanka and the rest of the world including surplus and shortage management; traditional and modern methods of water management in Sri Lanka: harnessing water resources for sustainable development.">Advanced Hydrology </a></span> <br/>
                <span>GGY433</span> <span><a href="" title="The study of landforms, processes and sedimentary formations is known as Coastal Geomorphology which is concerned about the development of landforms in the land-sea interface area under the influence of both marine and terrestrial processes.  The main topics covered in this course include, nature of the coastlines: their origin and evolution, composition, controlling and forcing mechanism; coastal landforms andtheirbehavioral characteristics; coastal sediments and their stratigraphic characteristic; coastal erosion; marine processes:  waves, tides, currents, fluctuation of sea level; dynamic coastal geomorphic systems functioning under different temporal and spatial scales; coastal landforms in Sri Lanka.  ">Coastal Geomorphology</a> </span> <br/><br/>
                <span>Optional List 1</span> <span>Geographical Skills </span> <br/>
                <span>GGY450</span> <span><a href="" title="This course will  cover the following topics: Introduction to the science and art of Remote Sensing; remote sensing systems; Radiation and Electromagnetic Spectrum; energy interactions in the atmosphere;  photographic and multispectral remote sensing; satellite platforms and sensor systems;  spectral and temporal resolution of imagery;    passive and active remote sensing systems;  methods of spectral and spatial enhancement, image rectification;  digital image processing;  geometric and radiometric corrections  image classifications;  pattern recognition;  image analysis and interpretation; Remote Sensing applications. Aerial photography and elements of Photogrammetry. ">Remote Sensing </a></span> <br/>
                <span>GGY451</span> <span><a href="" title="The course covers the major themes of Geographic Information Science (GIS).  The specific areas covered are scope and methods of GIS, space-time concepts, cartographic representation and modelling of geographic space,  temporal GIS, the Geographic Information Science debate;  GIS and Geography; the nature, type and quality of geographic data;  data errors; geographic data sources; scale and resolution of geographic data; spatial data infrastructure: data standards; database concepts and models; spatial analysis: 3D analysis; network analysis, geo-statistical analysis;  geo-visualization; methods of digital data capture: GPS survey;  GIS in decision making; GIS applications. ">Advanced Geographic Information System </a></span> <br/>
                <span>GGY452</span> <span><a href="" title="Introduction:  Basic concepts of space and location;  spatiality of human behaviour; spatial factors in decision making;  factors affecting the location of  human activities and how they have changed over time; analytical techniques in five geographical patterns: movements, networks, nodes, hierarchies and surfaces; locational models in agriculture (e.g. Von Thunen), industry (e.g. Weber), cities (e.g. Burgess), transport (e.g. density analysis) and services and settlements (e.g. Christaller);  regional development and change: Perroux, Hirschman, Myrdal, electoral analysis etc.;  new location factors affecting locational decisions in a globalizing world.  These models will be applied to Sri Lankan context in the form of class exercises.">Locational Analysis </a></span> <br/>
                <span>GGY454</span> <span><a href="" title="The specific topics include qualitative research and its place in Geography ; subjectivity-objectivity debate; importance of qualitative research; qualitative research design; qualitative reseach methods; interviews; focus groups; observational research (including participatory observation); reading texts and textual analysis; qualitative data collection issues; coding and processing qualitative data; qualitative data analysis; computer application and qualitative data analysis; presenting qualitative research findings; writing qualitative geographies.">Qualitative Methods in Geography</a> </span> <br/><br/>
                <span>Optional List 2</span> <span>Applied Geography </span> <br/>
                <span>GGY475</span> <span><a href="" title="Introduction:  sustainable development concepts; multidisciplinary approaches to development; use of EIA as means of achieving sustainable development goals; Introduction to EIA process and its pros and cons; key elements in EIA : alternatives, impact area, significant impacts, mitigation and monitoring; EIA process in Sri Lanka: prescribed list, procedure, and administration; methods of EIA; identification and assessment of impacts on physical, biological and social environment; national involuntary resettlement policy and EIA; role of public participation in EIA; valuation of environmental impacts and  Extended (environmental) benefit cost Analysis; organization of a EIA study and EIA report; Analysis of EIA’s.">Environmental Impact Assessment </a></span> <br/>
                <span>GGY476</span> <span><a href="" title="Introduction: a comparison between natural and social systems; scope of SIA: the need for SIA, and a brief history of SIA;  society and social constitution: levels of social organization; social concerns of development: impacts and social reactions; theories of society: Weber, Durkheim, Marx and Giddens; principles  and steps of SIA; techniques and social scoping; PRA theory and SIA; cultural impact assessment; gender impact assessment; involuntary resettlement policy and practice; variables of SIA applicable to Sri Lanka; Social Safeguards of international agencies; methods of Social Impact Assessment: case studies analysis; SIA or Social Audit exercise.">Social Impact Assessment </a></span> <br/>
                <span>GGY477</span> <span><a href="" title="Importance of NR and NRM;  concepts and theories of NRM; evolution of natural resource management; instruments of NRM: policy, legal and institutional, market instruments, cultural practices; natural resources management conflicts and issues: air and industrial pollution, water resources and pollution, oceanic recourses, waste management, land degradation and soil conservation, mangroves management, encroachment of critical areas; threat to endangered species: land use change, energy resources and climate change; community integrated natural resources management: case studies from Sri Lanka and selected countries.">Natural Resource Management </a></span> <br/>
                <span>GGY478</span> <span><a href="" title="The main topics of this course include: introduction to the field; key theoretical debates and discourses on gender and development from a historical perspective: concept of gender; geography and gender;  feminist research in geography; theories of women, gender and development;   feminist theories- liberal, radical, postmodern, post colonial and eco-feminism;  evolution of gender/women in development theories and practices: women in development (WID), women and development (WAD), gender and development (GAD), women and environment and development (WED), women culture and development (WCD);  gender and policy approaches to development: welfare, equity, anti-poverty, efficiency and empowerment approaches; Geographies of work and gender (women in the local and global economies): gender and agriculture, gender and industry, gender and migration, gender and poverty; women organizing for change (SEWA, Women and Labour movements); mainstreaming gender into development planning;  gender planning.The course will draw empirical studies and examples from Sri Lanka and selected countries.">Gender & Development </a></span> <br/>
                <span>GGY479</span> <span><a href="" title="Introduction to disasters; types of disasters: natural and human induced: causes of disasters:
impacts of disasters: disaster management cycle : disaster strikes, emergency response, relief, rehabilitation, mitigation, and preparedness:pre-disaster impact assessment (Pre-DIA):post-disaster impact assessment (PDIA): spatial tools in disaster management: Geographical Information Systems (GIS)  and Remote Sensing (RS; community resilience and response; institutional role: Government (GOs), non-government (NGOs) and international organizations: early warning systems on disasters: country experiences: disaster management acts in Sri Lanka:disaster management in Sri Lanka:disaster management training/field work:disaster management training/field work.
">Disaster Management</a></span> <br/>
                <span>GGY480</span> <span><a href="" title="Introduction to the Coastal Zone and Coastal Environment;  physical, biological and social components of the coastal system;  coastal morphology;  types of coastal ecosystems;  
coastal processes and forces; sediment budget: erosion and accretion; coastal hazards and risks; strategies in coastal zone management; coastal management issues in Sri Lanka;coastprotectionmeasures; history of coast protection in Sri Lanka; institutional and legal framework for coastal protection in Sri Lanka; climate change impacts on the coastal zone and management options.">Coastal Zone Management </a></span> <br/>
                <span>GGY481</span> <span><a href="" title="Identification of  a watershed;  watershed as an open system; classification of  watersheds;  watershed  degradation and causes: land degradation, deforestation, incompatible land use practices; watershed management: definitions, approaches: mechanical, agronomic and socio-economic aspects; irrigation and water management: soil conservation and land management, eco-systems and forest management, social and institutional development, holistic aspects;  management strategies and sustainability; economics of  watershed management;  participatory integrated watershed management; watershed management policies and implementation issues; case studies: watershed management projects.">Watershed Management</a></span> <br/>
                <span>GGY482</span> <span><a href="" title="Conceptual and theoretical introduction to tourism geography; The demand and supply in tourism; urban recreation and tourism; rural recreation and tourism; tourism and recreation in the pleasure periphery: wilderness and national parks; coastal and marine recreation and tourism; heritage tourism: ecotourism; the impacts of tourism on culture and environment; tourism and recreation planning and policy; Ethics and tourism planning; tourism and environmental planning; tourism Geography in Sri Lanka:  issues, challenges and opportunities.">Tourism Geography </a></span> <br/>
                <span>GGY483</span> <span><a href="" title="The course covers both theoretical and empirical knowledge derived from both international and national contexts.  The course will cover the following topics: Introduction: What is land use planning?; fundamentals of spatial planning; environmental context of planning; social context of planning (economic, political, cultural); theoretical perspectives on land use: agricultural, industrial, urban, rural and regional;  Understanding the planning environment: legislations and policy; politics of land use planning and national planning; methods and techniques of land use planning: inventory and analysis of existing land use, identifying and evaluating the potential needs and the constraints, mitigation, GIS as an effective tool of land use planning; case studies: analysis of selected land use plans (urban, agricultural, regional, watershed); land use planning for a sustainable society. During the course, the students will develop a land use plan for a selected area as a practical exercise.">Land-use Planning</a></span> <br/>
                <span>GGY485</span> <span><a href="" title="While this course emphasizes the importance of place, space and spatiality in understanding the geographical worlds of children, it inevitably cuts across inter- and intra-disciplinary boundaries. Specific topics covered include, Theoretical perspective: children and geography; Childhood as socially constructed; Issues both of a structural nature, which has an implication for children's everyday lives and childhood, as well as children's agency in defining and giving meaning to their lives and activities; methodological approaches towards children as informants in the research process: various forms of interviews; observations, visual methods and fieldwork; Methodological issues; research ethics; quantitative approaches; Empirical issues (emphasis will be given to Sri Lankan context):children in difficult circumstances: Street children; children and armed conflicts, child labour ; children, migration and social change; children and education; childhood poverty; Children and health; Commercialization of children; Globalization and children; International actions for children.">Children & Geography </a></span> <br/>
                <span>GGY486</span> <span><a href="" title="Introduction to forest resource management; interactions between forests and people; importance of forests in traditional farming systems; livestock economy and forests; Industrial economy and forests;  Social and cultural factors of forest management;  
deforestation, reforestation and afforestation; forest conflicts; wildlife and human conflicts; peoples movement in forest conservation; gender dimension of forest management; tribes and forests; pastoralists and their dependence on forests; forest rights; customary rights of people; community participation in forest management; management of common property resources and open access resources; forest management and sustainable livelihood strategies; forests and food security; eco-tourism and local development; land use change and forestry; role of non-governmental organizations and community based organizations in forest management; forest management tools and strategies:  traditions and customs, policies and laws, certification, market;  forest resource management in Sri Lanka:  issues, challenges and opportunities.  (Field trip to the Forest Department).
">Forest Resource Management </a></span> <br/>
                <span>GGY488</span> <span><a href="" title="The course will focus on three sections. Theoretical background to sustainable development: theories of human-environmental relationship; theories of development; discourse on sustainable development;  Geography and sustainable development symbiotic relationship between physical and human environment: environmental problems and causes, natural resource management: water, energy, land, forest, mineral, coastal and biological diversity, and socio-spatial sustainability; Sustainable development practices: environmental management, impact assessments (environmental, social, gender, cultural etc), environmental quality and poverty;  Measuring sustainable development: traditional indicators and new indicators; Global and national strategies for achieving sustainable development.
">Sustainable Development</a></span> <br/>
                <span>GGY489</span> <span><a href="" title="The course focuses on methods, techniques and strategies of regional development planning, reviewing the concepts and theories, various types of regional development programmes in both developed and developing countries.  The main topics covered in the course: regional /spatial inequalities; fundamental of regional planning; analysis of the regional structures on natural resource base: growth potentials; settlement patterns; river basin development approach:  agropolitan development approach; theories of regional development and their application; preparation of regional development plans and implementation; experiences of regional development programmes in developed and developing countries; regional planning and development in Sri Lanka; Issues, challenges and opportunities in regional planning.">Regional Planning & Development </a></span> <br/><br/>
                <h4>Courses for BA (General) Degree</h4>
                <br/>
                <span>Compulsory Courses</span> <br/>
                <span>GGY213</span> <span><a href="" title="The course will pay attention to five major areas; 1) The changing nature of  Economic Geography: growth and significance as a sub field, changing trends and modern Focus, 2) Spatial organization of economic activities: agriculture, industry, services 3) Geography of the world economy: economic patterns and trends: industry and finance, agriculture, economic inequality, international trade  4) Spatial transformations in the world economy: rise of core and periphery: European world system, industrial core, globalization of  production, spatial transformation of the periphery: colonial economies and spatial change, industrialization in the periphery, changing nature of agriculture 5) Regions and localities within the world economy: South Asia and Sri Lanka.">Economic Geography</a></span> <br/>
                <span>GGY214</span> <span><a href="" title="The course will cover geological/geomorphological, hydrological and biological components and processes of the environment and their interdependence; geological/geomorphological processes: geological evolution, endogenic and exogenic processes, landforms; climate and hydrology: general circulation model, surface hydrology, ground water hydrology; biological: evolution, extinction and changes, vegetation development, succession and climax communities, ecosystems (diversity & stability) , major biomes, biodiversity; natural hazards: geological hazards, climatic hazards/extreme climates, biological issues, human impacts on ecosystems.">Advanced Physical Geography</a> </span> <br/><br/>
                <span>GGY303</span> <span><a href="" title="Part One: Introduction to physical environment; Geology: structure and tectonics, relief and drainage, landforms, soils, minerals, water resources; Climate: circulation and seasonal regime, temperature, rainfall, and climate change; biological environment:  natural vegetation, agro-ecology,  marine environment, natural hazards and disasters: landslides, floods, droughts, cyclones, tornados, and tsunami
Part Two: Introduction to social environment; population: growth, distribution and density, ethnicity and religion, urban and rural settlements;agriculture:types and spatial patterns and major issues; Industries: types and spatial patterns and problems; Services (spatial inequalities in education, health, welfare and consumer services; patterns of international trade; challenges and opportunities: environment management, poverty eradication, national integration and globalization.
">Geography of Sri Lanka </a></span> <br/>
                <span>GGY313</span> <span><a href="" title="At the beginning of each region there will be a brief overview covering physical, cultural, historical and political background of the region and issues unique to that region. Introduction: basic geographic concepts, issues and regions; Europe: industrialization/urbanization, devolution and new challenges, European integration, sub-regions; Russian region: political history, economic transition and development challenges; North America: pluralistic social structure, post-industrial transformation, regionalization, sub-regions; Middle America: uncertain economic development, sub regions; South America: economic development, sub-regions; Northern Africa and Middle East: resource and the world economy, foreign intervention, sub regions; Africa South of Sahara: region in economic and political crisis, effect of colonization, development perspective, sub-regions; South Asia: European political history, development challenges, sub regions; East Asia: economic transformation and global influence; Southeast Asia: political colonial history, development challenges/transformation, sub regions; Oceania: political colonial history, challenges; unique regions of the world: polar, mountains, desert.">World Regional Geography</a> </span> <br/><br/>
                <span>Optional Courses</span>  <br/>
                <span>GGY201</span> <span><a href="" title="This is an introductory course in Geomorphology covering the major processes of landform  development of evolution. The topics cover under this course include: major geomorphological processes and methods, theories and thoughts of landform development, erosion cycle, relationship between different lithological characteristics and geomorphological features, endogenic processes (plate tectonics, diastrophism, etc.), exogenic processes (rock weathering, formation of hill slopes, climatic geomorphology, fluvial, aeolian, coastal, glacial processes and landforms, etc.), quantitative and qualitative methods of geomorphological studies, geomorphological features of Sri Lanka.">Geomorphology </a></span> <br/>
                <span>GGY202</span> <span><a href="" title="This course covers both theoretical and practical aspects of cartography; The main topics are:
introduction to cartography (the history and the nature of cartography, types of maps etc.); map scale, map projections and coordinate systems, principles of cartographic design (map elements, visual variables and map symbolization, color theory, typography and lettering, map compilation etc.) analysis of map features (physical and cultural features using both quantitative and qualitative methods), statistical cartography, construction and interpretation of weather maps, interpretation of aerial photographs, introduction to Geographic Information Systems.
">Cartography </a></span> <br/>
                <span>GGY204</span> <span><a href="" title="The main topics of the course include, the difference between population geography and demography; population theories and debates: Malthusian and Marxian perspective, Bucharest and recent debates, demographic transition theory; world population distribution and related issues, main factors and processes affecting population size and distribution; demographic techniques of data collection and analysis; and visualization; population movements: migration theories, historical and modern trends of migration; population in Sri Lanka (distribution and new trends); introduction to research frontiers in population geography.
">Population Geography </a></span> <br/>
                <span>GGY206</span> <span><a href="" title="Introduction to Geology,  definition of a mineral, classification of minerals, physical properties of minerals , identification of minerals, rock cycle, igneous rocks (formation, structures, classification), sedimentary rocks  formation, structures, classification), metamorphic rocks  formation, structures, classifications), rock identification, rock deformation and geological structures in rocks, different types of rocks in Sri Lanka, stratigraphical units, unconformities, introduction to paleontology, identification of fossils, introduction to photogeology.">Geology </a></span> <br/><br/>
           <span>GGY310</span> <span><a href="" title="This course will cover the following topics: historical evolution of the settlements: origin and growth; types of settlements: rural, urban, and other; ecological processes of rural and urban growth; settlement functions and networks; spatial patterns of the settlements: spatial hierarchies and  internal morphologies;  settlement  and landscapes: settlements as instruments of social, economic,  colonial and cultural articulation; measuring settlement patterns: nearest neighbour analysis, the rank size rule,  primate city, central place theory;   settlement policies and planning in Sri Lanka. ">Settlement Geography</a> </span> <br/> 
           <span>GGY311</span> <span><a href="" title="Introduction to Biogeography:  link between biology and geography; theoretical and conceptual development of the field; The concept of biosphere: origin and evolution of organisms; biological kingdoms; the theory of island biogeography; the concept of carrying capacity; geographical distribution of biota; biogeographic realms and major biomes: Wallace’s biogeographical regions; The concept of biodiversity: genetic diversity, species diversity and  ecosystem diversity/habitat diversity, biodiversity degradation; biological interactions.  society and biological resources: the concept of conservation, challenges and conservation measures in national and international contexts(special attention will be paid to in – situ and ex – situ conservation practices in Sri Lanka); Biological survey methods (practical exercise based on a field visit); conservation Biogeography ( The roots of conservation Biogeography, social values of conservation Biogeography, systematic conservation – past, present & future).">Biogeography </a></span> <br/>
           <span>GGY312</span> <span><a href="" title="This course will cover the following topics: the concepts and theories of Urban Geography; the process of urbanization: origin and growth of urban settlements; evolution of urban systems: form, structure and organization of cities; urban functions: commercial, residential, services etc.; urban land use planning; urban problems and prospects; cities of future; urbanization in Sri Lanka; Urban policies and planning in Sri Lanka.">Urban Geography </a></span>--> <br/> 
           <br/>  
           <h4>Download Course Details </h4>           
           <span><a href="../assets/downloads/100.pdf">First Year Courses</a></span><br/>
           <span><a href="../assets/downloads/200.pdf">Second Year Courses</a></span><br/>
           <span><a href="../assets/downloads/300.pdf">Third Year Courses</a></span><br/>
           <span><a href="../assets/downloads/400.pdf">Fourth Year Courses</a></span><br/>
            
                </div>
                
           </div>
        </div>
	</div>

	<?php require_once "../assets/footer.php" ?>
</body>
</html>